import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <div className="flex flex-col h-svh max-h-svh items-center py-3 px-2 lg:px-4">
          <div className="flex space-x-2 items-center lg:justify-center w-full px-2 lg:mt-6 lg:px-4">
            <img
              src={process.env.NEXT_PUBLIC_LOGO_URL}
              alt="logo"
              className="size-12 rounded-xl border object-cover"
            />
            <h1 className="font-bold text-xl">
              {process.env.NEXT_PUBLIC_COMPANY_TITLE}
            </h1>
          </div>
          <div className="w-full max-w-sm lg:max-w-md h-full mt-3 lg:my-12">
            <div className="h-full w-full rounded-xl border overflow-clip">
              {children}
            </div>
            <p className="lg:block hidden text-center text-xs w-full mt-4">
              Powered by <b>{process.env.NEXT_PUBLIC_COMPANY_TITLE}</b>
            </p>
          </div>
        </div>
      </body>
    </html>
  );
}
